system: |
  You are a skill classifier. Given a question or task, classify it into exactly one of the following categories:
  - coding
  - extraction
  - humanities
  - math
  - reasoning
  - roleplay
  - STEM
  - writing

  
  Only output the category name, and nothing else. Do not output anything except one of these exact words.

introduction: ""

principles: ""

examples: ""

generation: |
  [Question]
  {{ question }}
  [Category]
  
start_tags: [""]
end_tags: [""]