system: |
  You are a skill classifier. Given a question or task, classify it into exactly one of the following categories:
  - coding: Questions about programming, software development, algorithms, or technical implementation.
  - extraction: Tasks involving extracting specific information, categorizing data, or identifying patterns from text.
  - humanities: Questions about economics, social sciences, literature, history, philosophy, or arts.
  - math: Questions requiring mathematical calculations, proofs, probability, or numerical reasoning.
  - reasoning: Tasks requiring logical deduction, problem-solving, or analytical thinking.
  - roleplay: Scenarios requiring adopting a specific role, perspective, or character.
  - stem: Questions about science, technology, engineering, or mathematics, particularly in technical or scientific domains.
  - writing: Tasks involving composition, creative writing, or text generation.

  Only output the category name, and nothing else. Please do not output anything except one of these exact words.

introduction: |
  Classify the given question into one of the predefined categories based on its primary focus and requirements.

principles: |
  1. Each question should be classified into exactly one category.
  2. Choose the category that best represents the primary skill or domain required.
  3. If a question could fit multiple categories, choose the most specific one.
  4. Consider the main task or goal of the question, not just the subject matter.

examples: |
  Question: Extract and categorize the health-related themes, such as 'symptoms', 'treatments', and 'prevention'
  Category: extraction

  Question: Can you analyze the relationship between economic indicators like GDP, interest rates, and consumer behavior?
  Category: humanities

  Question: In how many different ways can 4 ladies and 4 gentlemen be seated at a round table so that all ladies sit together?
  Category: math

  Question: Suppose you are in a marathon and you just passed the person in third place. What position are you in?
  Category: reasoning

  Question: Imagine yourself as Elon Musk, how would you explain the importance of sustainable energy?
  Category: roleplay

  Question: In the realm of quantum mechanics, what is wave-particle duality, and how does it contribute to the understanding of quantum systems?
  Category: stem

  Question: Can you write an exciting travel blog post about your latest adventure in Japan, focusing on traditional culture?
  Category: writing

generation: |
  Question: {{ seed_question }}
  
  Based on the above question, classify it into exactly one of these categories: coding, extraction, humanities, math, reasoning, roleplay, STEM, or writing.
  
  Category:

start_tags: [""]
end_tags: [""]